<table class="table">
	<tr>
		<th>Author</th>
        <th>Title</th>
        <th>Year</th>
        <th>Language</th>
        <th>Genre</th>
        <th>Location</th>
        <th style="width: 120px;"></th>
	</tr>
    <tbody>
        <?php if(count($books) > 0): ?>
            <?php foreach ($books as $book): ?>
                <tr>
                    <td><?=$book['author'] ?></td>
                    <td><?=$book['title'] ?></td>
                    <td><?=$book['published_year'] ?></td>
                    <td><?=$book['language'] ?></td>
                    <td><?=$book['genre'] ?></td>
                    <td><?=$book['location'] ?></td>
                    <td class="icon-cell">
                        <a href="<?=$router->urlFor('book-detail', ['id' => $book['book_id']])?>" class="btn btn-primary btn-circle material-icons">create</a>
                        <a href="<?=$router->urlFor('book-copy', ['id' => $book['book_id']])?>" class="btn btn-primary btn-circle material-icons">file_copy</a>
                        <a href="<?=$router->urlFor('book-delete', ['id' => $book['book_id']])?>" class="btn btn-primary btn-circle material-icons">delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4" style="text-align: center;"><i>No books found</i></td>
            </tr>
        <?php endif; ?>
    </tbody>

</table>

<a type="button" class="btn btn-primary" href="<?=$router->urlFor('book-new')?>">New</a>
<a type="button" class="btn btn-primary" href="<?=$router->urlFor('home')?>">Back</a>
