<table class="table">
	<tr>
		<th>Title</th>
		<th>Author</th>
		<th>Year</th>
        <th style="width: 120px;"></th>
	</tr>
    <tbody>
        <?php if(count($books) > 0): ?>
            <?php foreach ($books as $book): ?>
                <tr>
                    <td><?=$book['title'] ?></td>
                    <td><?=$book['author'] ?></td>
                    <td><?=$book['published_year'] ?></td>
                    <td class="icon-cell">
                        <a href="<?=$router->urlFor('book-detail', ['id' => $book['book_id']])?>" class="btn btn-primary material-icons">create</a>
                        <a href="<?=$router->urlFor('book-delete', ['id' => $book['book_id']])?>" class="btn btn-primary material-icons">delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4" style="text-align: center;"><i>No books found</i></td>
            </tr>
        <?php endif; ?>
    </tbody>

</table>

<a type="button" class="btn btn-primary" href="<?=$router->urlFor('book-new')?>">New</a>
<a type="button" class="btn btn-primary" href="<?=$router->urlFor('home')?>">Back</a>
