<div class="card form-card">
	<div class="card-body">
		<form action="<?=$router->urlFor('book-save')?>" method="post">

			<div class="form-group">
				<label for="input-title" class="bmd-label-floating">Title</label>
				<input class="form-control" type="text" id="input-title" name="title" value="<?=$book['title'] ?>">
			</div>

			<div class="form-group">
				<label for="input-author" class="bmd-label-floating">Author</label>
				<input class="form-control" type="text" id="input-author" name="author" value="<?=$book['author'] ?>">
			</div>

			<div class="form-group">
				<label for="input-year" class="bmd-label-floating">Year (YYYY)</label>
				<input class="form-control" type="text" id="input-year" name="year" value="<?=$book['published_year'] ?>"  pattern="^\d{4}$">
			</div>

			<div class="form-group">
				<label for="input-location" class="bmd-label-floating">Location</label>
				<select class="form-control" id="input-location" name="location">
					<option value="" label="none">none</option>
					<?php foreach ($locations as $locId => $location): ?>
						<option value="<?=$locId ?>" label="<?=$location ?>" <?php if($locId == $book['loc_id']): ?>selected <?php endif; ?>>
							<?=$location ?>
						</option>
					<?php endforeach; ?>
				</select>
			</div>

			<div class="form-group">
				<label for="input-genre" class="bmd-label-floating">Genre</label>
				<select class="form-control" id="input-genre" name="genre">
					<option value="" label="none">none</option>
					<?php foreach ($genres as $genreId => $genre): ?>
						<option value="<?=$genreId ?>" label="<?=$genre ?>" <?php if($genreId == $book['genre_id']): ?>selected <?php endif; ?>>
							<?=$genre ?>
						</option>
					<?php endforeach; ?>
				</select>
			</div>

			<input type="hidden" name="id" value="<?=$book['book_id'] ?>">

			<div class="btn-group" role="group" aria-label="Book Actions">
			    <button type="submit" class="btn btn-primary">Save</button>
			    <a class="btn btn-primary" href="<?=$router->urlFor('books')?>">Back</a>
			</div>

		</form>
	</div>
</div>