<table class="table">
	<tr>
		<th>Genre</th>
		<th>Sub-Genre</th>
		<th style="width: 120px;"></th>
	</tr>

	<tbody>
        <?php if(count($array_genre) > 0): ?>
			<?php foreach ($array_genre as $genre): ?>
				<tr>
					<td><?=$genre['genre'] ?></td>
					<td><?=$genre['sub_genre'] ?></td>
					<td class="icon-cell">
	                    <a href="<?=$router->urlFor('genre-detail', ['id' => $genre['genre_id']])?>" class="btn btn-primary btn-circle material-icons">create</a>
	                    <a href="<?=$router->urlFor('genre-delete', ['id' => $genre['genre_id']])?>" class="btn btn-primary btn-circle material-icons">delete</a>
					</td>
				</tr>

			<?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="3" style="text-align: center;"><i>No genres found</i></td>
            </tr>
        <?php endif; ?>
	</tbody>
</table>

<div class="btn-group" role="group" aria-label="Genre Actions">
    <a type="button" class="btn btn-primary" href="<?=$router->urlFor('genre-new')?>">New</a>
    <a type="button" class="btn btn-primary" href="<?=$router->urlFor('home')?>">Back</a>
</div>
