
<table class="table">
	<tr>
		<th>Location</th>
		<th>Room</th>
		<th>Storage</th>
        <th style="width: 120px;"></th>
	</tr>

    <tbody>
        <?php if(count($locations) > 0): ?>
            <?php foreach ($locations as $location): ?>

                <tr>
                    <td><?=$location['location'] ?></td>
                    <td><?=$location['room'] ?></td>
                    <td><?=$location['storage'] ?></td>
                    <td class="icon-cell">
                        <a href="<?=$router->urlFor('location-detail', ['id' => $location['loc_id']])?>" class="btn btn-primary btn-circle material-icons">create</a>
                        <a href="<?=$router->urlFor('location-delete', ['id' => $location['loc_id']])?>" class="btn btn-primary btn-circle material-icons">delete</a>
                    </td>
                </tr>

            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4" style="text-align: center;"><i>No locations found</i></td>
            </tr>
        <?php endif; ?>
    </tbody>

</table>

<div class="btn-group" role="group" aria-label="Location Actions">
    <a type="button" class="btn btn-primary" href="<?=$router->urlFor('locations-new')?>">New</a>
    <a type="button" class="btn btn-primary" href="<?=$router->urlFor('home')?>">Back</a>
</div>
