<div class="mdc-data-table">
    <table class="mdc-data-table__table">
    	<tr class="mdc-data-table__header-row">
    		<th class="mdc-data-table__header-cell">Location</th>
    		<th class="mdc-data-table__header-cell">Room</th>
    		<th class="mdc-data-table__header-cell">Storage</th>
            <th class="mdc-data-table__header-cell"></th>
    	</tr>

    <tbody class="mdc-data-table__content">
    <?php foreach ($locations as $location): ?>

        <tr class="mdc-data-table__row" onclick="window.location = '<?=$router->urlFor('location-detail', ['id' => $location['loc_id']])?>'">
            <td class="mdc-data-table__cell"><?=$location['location'] ?></td>
            <td class="mdc-data-table__cell"><?=$location['room'] ?></td>
            <td class="mdc-data-table__cell"><?=$location['storage'] ?></td>
            <td>
                <a href="<?=$router->urlFor('location-delete', ['id' => $location['loc_id']])?>" class="mdc-icon-button material-icons">delete</a>
            </td>
        </tr>

    <?php endforeach; ?>
    </tbody>

    </table>
</div>

<br><br>

<a class="mdc-button" href="<?=$router->urlFor('locations-new')?>">
  <div class="mdc-button__ripple"></div>
  <span class="mdc-button__label">New</span>
</a>

<a class="mdc-button" href="<?=$router->urlFor('home')?>">
  <div class="mdc-button__ripple"></div>
  <span class="mdc-button__label">Back</span>
</a>
