<div class="card form-card">
	<div class="card-body">
		<form action="<?=$router->urlFor('location-save')?>" method="post">

			<div class="form-group">
				<label for="input-location" class="bmd-label-floating">Location</label>
				<input class="form-control" type="text" id="input-location" name="location" value="<?=$location['location'] ?>">
			</div>

			<div class="form-group">
				<label for="input-room" class="bmd-label-floating">Room</label>
				<input class="form-control" type="text" id="input-room" name="room" value="<?=$location['room'] ?>">
			</div>

			<div class="form-group">
				<label for="input-storage" class="bmd-label-floating">Storage</label>
				<input class="form-control" type="text" id="input-storage" name="storage" value="<?=$location['storage'] ?>">
			</div>

			<input type="hidden" name="id" value="<?=$location['loc_id'] ?>">

			<div class="btn-group" role="group" aria-label="Location Actions">
			    <button type="submit" class="btn btn-primary">Save</button>
			    <a class="btn btn-primary" href="<?=$router->urlFor('locations')?>">Back</a>
			</div>

		</form>
	</div>
</div>