<html>
<head>
	<title>Bibliothek</title>
	<link href="https://unpkg.com/material-components-web@v4.0.0/dist/material-components-web.min.css" rel="stylesheet">
	<script src="https://unpkg.com/material-components-web@v4.0.0/dist/material-components-web.min.js"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="/bibliothek/styles.css">
</head>
<body>
	<header class="mdc-top-app-bar mdc-top-app-bar--fixed">
		<div class="mdc-top-app-bar__row">
			<section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
				<span class="mdc-top-app-bar__title"><?=$mainTitle ?></span> </section>
				<section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end">
				</section>
			</div>
		</header>
		<div class="mdc-top-app-bar--fixed-adjust">
			<div class="main-content">
				<?=$content?>
			</div>
		</div>
	</body>
	</html>